### ISSUE TITLE
[FEAT] Option to run rootless mode

### ISSUE THREAD

**Issue by shin-san** [linuxserver/docker-syslog-ng#14]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I have currently deployed the following container in a root-access disabled k8s cluster and encountered the following error log during deployment:
```
s6-overlay-suexec: warning: unable to gain root privileges (is the suid bit set?)
s6-mkdir: warning: unable to mkdir /run/s6: Permission denied
s6-mkdir: warning: unable to mkdir /run/service: Permission denied
s6-overlay-suexec: fatal: child failed with exit code 111
``` 
This is currently preventing me from deploying it and was wondering if a rootless mode would be something that can be introduced to allow its deployment.

### Reason for change

Allow rootless mode for the container to be deployed and run in an rootless container orchestration platform

**Comment by Roxedus** [comment]
We do not have any immediate plans to support rootless across our fleet.
