### ISSUE TITLE
Unable to find image 'lscr.io/linuxserver/syslog-ng:latest' locally

### ISSUE THREAD

**Issue by ahowlett1965** [linuxserver/docker-syslog-ng#15]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On unRAID:
docker run
  -d
  --name='syslog-ng'
  --net='bridge'
  -e TZ="Europe/London"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="ExternalServer"
  -e HOST_CONTAINERNAME="syslog-ng"
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/syslog-ng-logo.png'
  -p '514:5514/udp'
  -p '601:6601/tcp'
  -p '6514:6514/tcp'
  -v '':'/var/log':'rw'
  -v '/mnt/user/appdata/syslog-ng':'/config':'rw' 'lscr.io/linuxserver/syslog-ng'
Unable to find image 'lscr.io/linuxserver/syslog-ng:latest' locally
docker: Error response from daemon: Get "https://ghcr.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.

The command failed.

### Expected Behavior

I expected an install to complete

### Steps To Reproduce

Unraid 6.11.5, very limited configuration, with FreePBX installed but not running.

### Environment

```markdown
Unraid 6.11.5
Syslog package in Community Applications Plugin
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run
  -d
  --name='syslog-ng'
  --net='bridge'
  -e TZ="Europe/London"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="ExternalServer"
  -e HOST_CONTAINERNAME="syslog-ng"
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/syslog-ng-logo.png'
  -p '514:5514/udp'
  -p '601:6601/tcp'
  -p '6514:6514/tcp'
  -v '':'/var/log':'rw'
  -v '/mnt/user/appdata/syslog-ng':'/config':'rw' 'lscr.io/linuxserver/syslog-ng'
Unable to find image 'lscr.io/linuxserver/syslog-ng:latest' locally
docker: Error response from daemon: Get "https://ghcr.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.

The command failed.
```

### Container logs

```bash
Sorry, that is all I can find.
```

**Comment by thespad** [comment]
You've got a connectivity issue to GHCR. Could be transient, could be something like PiHole/Adguard blocking it, could be something else.

You can try one of our other mirrors like docker.io.
