### ISSUE TITLE
[BUG] credentials in ci

### ISSUE THREAD

**Issue by janneman001** [linuxserver/docker-syslog-ng#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi leaving credentials in ci/cd is not good practice. 
I don't known if you do this deliberatly or how far this goes as security risk right now
. 
Please look at:
GITHUB_TOKEN=credentials(
    GITLAB_TOKEN=credentials(

in your Jenkinsfile.....

### Expected Behavior

Credentials and tokens do not belong in SCM.

### Steps To Reproduce

Look at:
https://github.com/linuxserver/docker-syslog-ng/blob/main/Jenkinsfile

### Environment

```markdown
btw
Thanks for your docker-image it works out of the box!
```

### CPU architecture

x86-64

### Docker creation

```bash
I used default example.
```

### Container logs

```bash
...
```

**Comment by Roxedus** [comment]
Thank you for your concern! These are not actual credentials, rather just an uuid to the credential stored in Jenkins. They do not make sense outside the context of our CI.
