### ISSUE TITLE
Raspberry pi 5  Bookworm installation error - no matching manifest for linux/arm/v8

### ISSUE THREAD

**Issue by anvme** [linuxserver/docker-syslog-ng#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

# docker compose up -d
    [+] Running 0/1
     ⠧ syslog-ng Pulling        1.7s
    no matching manifest for linux/arm/v8 in the manifest list entries

### Expected Behavior

Run without problems

### Steps To Reproduce

Copy official compose.yml
docker compose up -d
And then error above

### Environment

```markdown
- OS: Raspberry pi 5, Raspbian GNU/Linux 12 (bookworm)
- How docker service was installed: Official docker repo
```

### CPU architecture

arm64

### Docker creation

```bash
233  sudo apt-get update
  234  sudo apt-get install ca-certificates curl
  235  sudo install -m 0755 -d /etc/apt/keyrings
  236  sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
  237  sudo chmod a+r /etc/apt/keyrings/docker.asc
  238  echo   "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
  239    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" |   sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  240  sudo apt-get update
  241  sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
```

### Container logs

```bash
Error response from daemon: No such container: syslog-ng
```

**Comment by thespad** [comment]
You have likely installed a 32-bit OS on your Pi because Rasbian *still* inexcusably default to it.

Run `sudo dpkg --print-architecture` to confirm.

**Comment by anvme** [comment]
64 bit

```
$ sudo dpkg --print-architecture
armhf

 # cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 12 (bookworm)"
NAME="Raspbian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=raspbian
ID_LIKE=debian

# cat /proc/version
Linux version 6.6.47+rpt-rpi-v8 (serge@raspberrypi.com) (gcc-12 (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT Debian 1:6.6.47-1+rpt1 (2024-09-02)

# uname -mrs
Linux 6.6.47+rpt-rpi-v8 aarch64

```

**Comment by aptalca** [comment]
`armhf` is 32 bit
so you have a 64 bit kernel but userland is 32 bit

**Comment by anvme** [comment]
It was raspberry pi os lite 64 bit
![Screenshot 2024-10-10 at 21 01 40](https://github.com/user-attachments/assets/00622209-5da2-46d3-94a9-68c634548831)

**Comment by thespad** [comment]
Unfortunately `dpkg` does not agree with you, and you've got 32bit userland packages installed, which is why Docker is trying to pull a non-existant image manifest.

**Comment by anvme** [comment]
Greetings, wanderer! 

If you too find yourself lost in the mysterious land of "no matching manifest" like I was, fear not! 
The ancient scrolls (aka Docker docs) have revealed the secret:
```
platform: linux/arm64
```
May your containers be plentiful and your errors few. Godspeed!
